### ISSUE TITLE
Sync issue between DB and ES

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#147]
Sometimes we face the  issue where the trait gets saved successfully in the DB. But the GET traits doesn't return the trait and when the user tries to add the trait again we get an error.

We have it already logged here
https://github.com/topcoder-platform/onboarding-processor/issues/39

Note: The trait shows up in a couple of minutes. 

https://user-images.githubusercontent.com/58783823/141416811-f7ee7134-9973-42f4-9eb5-6644ae3d16c8.mov

<img width="1440" alt="Screenshot 2021-11-12 at 11 20 58 AM" src="https://user-images.githubusercontent.com/58783823/141416980-4ba6ec07-1827-4b79-b0cf-b9b824ea8147.png">
<img width="1440" alt="Screenshot 2021-11-12 at 11 21 19 AM" src="https://user-images.githubusercontent.com/58783823/141417018-3781c8ec-189c-40a7-9678-6c3e591b8927.png">

**Comment by lakshmiathreya** [comment]
cc @Oanh-and-only-Oanh

**Comment by vikasrohit** [comment]
@SathyaJayabal @lakshmiathreya it is the exact same situation which I mentioned in https://github.com/topcoder-platform/onboarding-processor/issues/39. And the reason you are seeing the language updated after some time, might be that some other profile update caused the ES to resync.

@rakibansary one possible solution could be as I mentioned somewhere else (don't remember the place), we have to check the error of the POST call and if it says `trait already exists`, we should make the PUT request with same payload instead of POST. That should solve most of the situations I guess.

**Comment by rakibansary** [comment]
Hi @SathyaJayabal,

This is ready for QA. Onboarding app, community app setitngs page both now uses v5 member Api. Additionally the onboarding processor has been updated to consistently store data across all clusters when a trait is updated so they are visible in search.

One known issue is when a user first signs up, their first name, last name & country are not saved as basic_info traits. The fix for this is in progress, but should not impact general sync.

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. Sync issue between DB and ES is resolved.


https://user-images.githubusercontent.com/55895538/145940595-ea6a0d7f-041c-419a-97c4-a2d801ddc9d1.mp4

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. No sync issues found
