### ISSUE TITLE
Page load not load when trying to continue from the Build Your Profile

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-onboarding-app#76]
Page load not load when trying to continue from the Build Your Profile
<img width="1440" alt="Screenshot 2021-11-08 at 11 53 15 AM" src="https://user-images.githubusercontent.com/58783823/140693990-a26272ca-97ab-4662-888b-374ca2a47e3f.png">

**Comment by rakibansary** [comment]
Steps to reproduce.

1. Navigate to https://platform.topcoder-dev.com/onboard/build-my-profile 
2. Enter Company Name, start date & end date only. Click "Complete your profile"

@nursoltan-s can you please take a look at this one. A similar issue was fixed in this commit https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/60/commits/6949d694665f09cd7b21edb58ae78c58a1da1053

Thanks

**Comment by SathyaJayabal** [comment]
@rakibansary . we are not able to delete the last entry.

for example:
1. Go to the https://platform.topcoder-dev.com/onboard/build-my-profile
2. add one new record for any of the categories (education, work or languages) and do not enter any data to the newly added record
3. delete all the other records in the category. 
4. Click on continue
Since all the fields are empty for the newly create record, the PUT operation is not made and the deleted records are not deleted in the BE

https://user-images.githubusercontent.com/58783823/140698000-3971f49b-2ece-460f-96bb-f417aa2e355a.mov

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-onboarding-app/pull/77

**Comment by SathyaJayabal** [comment]
verified on dev. not able to reproduce this issue now
